/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Kernel.Check
public import HexPermGroup.Build

public section

/-!
The compiled producer of kernel certificates, and the partition of their
Schreier pairs into bounded ranges.

`certify` reads the complete chain of `Group.ofGenerators`, keeps the levels
whose orbit has more than one point, and records packed generators, orbits,
transversals, inverse transversals, Schreier-tree edges and next-level
indices. The certificate is untrusted: only `check` gives it meaning.
-/

namespace Hex.PermGroup.Kernel

open Hex.Kernel

/-- A balanced `RArray` holding `xs[j]` at index `j`, for nonempty `xs`. -/
def rarrayOf {α : Type} [Inhabited α] (xs : Array α) : Lean.RArray α :=
  go xs.size 0 xs.size
where
  /-- Build the entries `lo ≤ j < hi`, with `fuel` bounding the depth. -/
  go : Nat → Nat → Nat → Lean.RArray α
    | 0, lo, _ => .leaf xs[lo]!
    | fuel + 1, lo, hi =>
      if hi ≤ lo + 1 then .leaf xs[lo]!
      else
        let mid := (lo + hi) / 2
        .branch mid (go fuel lo mid) (go fuel mid hi)

/-- The raw data of one chain level: base point, generators, orbit points and
transversal. -/
structure RawLevel (n : Nat) where
  base : Nat
  gens : Array (Perm n)
  points : Array (Fin n)
  reps : Array (Perm n)

/-- The levels of a chain with more than one orbit point. -/
def rawLevels : Chain n → Nat → List (RawLevel n)
  | .leaf _ _, _ => []
  | .cons level tail, base =>
    let rest := rawLevels tail (base + 1)
    if level.orbit.points.size ≤ 1 then rest
    else ⟨base, level.generators, level.orbit.points, level.orbit.reps.toArray⟩ :: rest

/-- Encode one level, given the packed generators of the next retained level. -/
def encodeLevel (n : Nat) (L : RawLevel n) (nextGens : List Nat) : Except String Level := do
  let W := width n
  let gens := L.gens.toList.map pack
  let o := L.points.size
  let orbit := L.points.map (·.val)
  let index : Array Nat := Id.run do
    let mut a := Array.replicate n 0
    for h : j in [0:o] do
      a := a.set! (L.points[j]'h.2.1).val (j + 1)
    return a
  let lookup := packFn W (fun x => index[x]!) n
  let reps := L.reps.map pack
  let invs := L.reps.map fun t => pack t.inv
  let mut parents : Array (Nat × Nat) := #[(0, 0)]
  for j in [1:o] do
    let x := orbit[j]!
    let mut found : Option (Nat × Nat) := none
    for h : i in [0:L.gens.size] do
      if found.isNone then
        let s := L.gens[i]'h.2.1
        let y := if hx : x < n then (s.inv.get ⟨x, hx⟩).val else 0
        let k := index[y]! - 1
        if index[y]! != 0 && k < j && comp n W (pack s) reps[k]! == reps[j]! then
          found := some (i, k)
    match found with
    | some e => parents := parents.push e
    | none => throw s!"no Schreier-tree edge reaches orbit point {x} at base {L.base}"
  let level : Level :=
    { base := L.base, size := o, gens := gens, orbit := rarrayOf orbit,
      reps := rarrayOf reps, invs := rarrayOf invs, parents := rarrayOf parents,
      lookup := lookup, next := [] }
  let mut next : Array (Nat × Nat) := #[]
  for t in nextGens do
    let mut found : Option (Nat × Nat) := none
    for i in [0:gens.length] do
      for j in [0:o] do
        if found.isNone && schreier n W level i j == t then
          found := some (i, j)
    match found with
    | some e => next := next.push e
    | none => throw s!"a next-level generator is not a Schreier generator at base {L.base}"
  return { level with next := next.toList }

/-- Encode the retained levels, each against the generators of the next. -/
def encodeLevels (n : Nat) : List (RawLevel n) → Except String Certificate
  | [] => pure []
  | L :: rest => do
    let nextGens := match rest with
      | [] => []
      | L' :: _ => L'.gens.toList.map pack
    let level ← encodeLevel n L nextGens
    let tail ← encodeLevels n rest
    return level :: tail

/-- The kernel certificate of the group generated by `S`. -/
def certify (S : Array (Perm n)) : Except String Certificate :=
  encodeLevels n (rawLevels (Group.ofGenerators S).chain 0)

/-! # Chunks -/

/-- Estimated kernel work, in field operations, of one sift through `rest`. -/
def siftCost (n : Nat) (rest : List Level) : Nat :=
  rest.foldl (fun acc L => acc + n + L.size.log2 + 2) n

/-- Estimated work of one Schreier pair of `L` followed by `rest`. -/
def pairCost (n : Nat) (L : Level) (rest : List Level) : Nat :=
  2 * n + L.size.log2 + siftCost n rest

/-- Estimated work of `levelOk` for `L` followed by `rest`. -/
def levelCost (n : Nat) (L : Level) (rest : List Level) : Nat :=
  let g := L.gens.length
  2 * L.size + 2 * n + g * g * n + 3 * L.size * n + (headGens rest).length * (2 * n + g * L.size)

/-- Estimated work of `inputsOk`. -/
def inputsCost (n inputCount : Nat) (c : Certificate) : Nat :=
  inputCount * siftCost n c + (headGens c).length * inputCount * n

/-- Split `[0, total)` into adjacent ranges of at most `step` pairs. -/
def ranges (total step : Nat) : List (Nat × Nat) :=
  (List.range ((total + step - 1) / step)).map fun r => (r * step, min total ((r + 1) * step))

/-- For each level, adjacent ranges of Schreier pairs whose estimated work is at
most `budget`, or the first check that cannot fit. -/
def chunks (n inputCount : Nat) (c : Certificate) (budget : Nat) :
    Except String (List (List (Nat × Nat))) := do
  if budget == 0 then throw "the chunk budget must be positive"
  let ic := inputsCost n inputCount c
  if ic > budget then
    throw s!"the input check needs about {ic} field operations, over the budget {budget}"
  let rec go : List Level → Nat → Except String (List (List (Nat × Nat)))
    | [], _ => pure []
    | L :: rest, ℓ => do
      let lc := levelCost n L rest
      if lc > budget then
        throw s!"the checks of level {ℓ} need about {lc} field operations, over the budget {budget}"
      let pc := pairCost n L rest
      if pc > budget then
        throw s!"one Schreier pair of level {ℓ} needs about {pc} field operations, \
          over the budget {budget}"
      let step := budget / pc
      let tail ← go rest (ℓ + 1)
      return ranges (L.gens.length * L.size) step :: tail
  go c 0

end Hex.PermGroup.Kernel
