/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Kernel.Check
public import HexPermGroup.Order
public import HexPermGroup.Cycles
public import HexPermGroup.Cycles.Order
public import HexPermGroup.Kernel.Span

public section

/-!
Soundness of the kernel certificate checker.

A packed number *represents* a permutation `σ` of `Fin n` when its fields
`0..n-1` are the images of `σ`. Bits at or above `n*W` are ignored. The proof
works from the last level of a certificate upward: sifting from a level
accepts exactly the packings of the subgroup generated by that level's
generators, the next level's subgroup is the stabilizer of the base point,
and each level gives a bijection with its orbit times the next subgroup.
-/

namespace Hex.PermGroup.Kernel

open Hex.Kernel

variable {n : Nat}

private theorem mul_assoc (p q r : Perm n) : (p * q) * r = p * (q * r) :=
  Perm.comp_assoc ..
private theorem mul_one (p : Perm n) : p * 1 = p := Perm.comp_id p
private theorem one_mul (p : Perm n) : 1 * p = p := Perm.id_comp p
private theorem inv_mul_cancel (p : Perm n) : p⁻¹ * p = 1 := Perm.inv_comp_self p
private theorem mul_inv_cancel (p : Perm n) : p * p⁻¹ = 1 := Perm.comp_inv_self p
private theorem inv_one : (1 : Perm n)⁻¹ = 1 := Perm.inv_id
private theorem inv_unique {p q : Perm n} (h : p * q = 1) : q = p⁻¹ := by
  have hh := congrArg (fun r : Perm n => p.inv.comp r) h
  simpa [← Perm.comp_assoc] using hh
private theorem inv_eq_iff_eq (p : Perm n) (x y : Fin n) : p.inv.get x = y ↔ x = p.get y :=
  ⟨fun h => by rw [← h]; simp, fun h => by rw [h]; simp⟩

@[simp] private theorem comp_cancel (p q : Perm n) : p.comp (p.inv.comp q) = q := by
  rw [← Perm.comp_assoc, Perm.comp_inv_self, Perm.id_comp]
@[simp] private theorem inv_comp_cancel (p q : Perm n) : p.inv.comp (p.comp q) = q := by
  rw [← Perm.comp_assoc, Perm.inv_comp_self, Perm.id_comp]

/-- `x` represents `σ`: its field `i` is `σ i` for every `i < n`. -/
@[expose] def Rep (n : Nat) (x : Nat) (σ : Perm n) : Prop :=
  ∀ i : Fin n, field (width n) x i.val = (σ i).val

/-- `x` is determined by its fields `0..n-1`, as the output of `packFn` is. -/
@[expose] def Canon (n : Nat) (x : Nat) : Prop :=
  x = packFn (width n) (fun i => field (width n) x i) n

theorem packFn_congr (W : Nat) {f g : Nat → Nat} :
    ∀ k, (∀ i < k, f i = g i) → packFn W f k = packFn W g k
  | 0, _ => rfl
  | k + 1, h => by
    rw [packFn_succ, packFn_succ, packFn_congr W k (fun i hi => h i (by omega)),
      h k (by omega)]

theorem canon_packFn (f : Nat → Nat) (hf : ∀ i < n, f i < 2 ^ width n) :
    Canon n (packFn (width n) f n) := by
  unfold Canon
  exact packFn_congr _ n fun i hi => (field_packFn _ f n hf i hi).symm

theorem canon_comp (x y : Nat) : Canon n (comp n (width n) x y) :=
  canon_packFn _ fun _ _ => field_lt _ _ _

theorem canon_ident : Canon n (ident n (width n)) :=
  canon_packFn _ fun _ hi => Nat.lt_trans hi (lt_two_pow_width n)

theorem canon_pack (p : Perm n) : Canon n (pack p) :=
  canon_packFn _ fun i hi => by
    simp only [hi, ↓reduceDIte]
    exact Nat.lt_trans (p.get _).isLt (lt_two_pow_width n)

theorem rep_pack (p : Perm n) : Rep n (pack p) p := fun i => by
  exact field_pack p i

theorem rep_ident : Rep n (ident n (width n)) 1 := fun i =>
  by simpa using field_ident (lt_two_pow_width n) i.isLt

theorem rep_comp {x y : Nat} {σ τ : Perm n} (hx : Rep n x σ) (hy : Rep n y τ) :
    Rep n (comp n (width n) x y) (σ * τ) := fun i => by
  simpa only [Perm.mul_def, Perm.get_comp] using
    (field_comp n (width n) x y i.isLt).trans ((congrArg (field (width n) x) (hy i)).trans (hx (τ.get i)))

theorem Rep.unique {x : Nat} {σ τ : Perm n} (hσ : Rep n x σ) (hτ : Rep n x τ) :
    σ = τ := by
  ext i
  rw [← hσ i, ← hτ i]

/-- A value that composes on the right with a representative of `τ` to the
identity represents `τ⁻¹`. -/
theorem rep_inv {x y : Nat} {τ : Perm n} (hy : Rep n y τ)
    (h : comp n (width n) x y = ident n (width n)) : Rep n x τ⁻¹ := fun i => by
  have h1 := field_comp n (width n) x y (τ⁻¹ i).isLt
  rw [h, field_ident (lt_two_pow_width n) (τ⁻¹ i).isLt, hy] at h1
  simpa using h1.symm

/-- Two canonical values with the same representative are equal. -/
theorem Canon.eq_of_rep {x y : Nat} {σ : Perm n} (hx : Canon n x) (hy : Canon n y)
    (hxσ : Rep n x σ) (hyσ : Rep n y σ) : x = y := by
  rw [hx, hy]
  exact packFn_congr _ n fun i hi => by rw [hxσ ⟨i, hi⟩, hyσ ⟨i, hi⟩]

/-! # Reading the Boolean checks -/

theorem allRange_iff (k : Nat) (p : Nat → Bool) : allRange k p = true ↔ ∀ i < k, p i = true := by
  simp [allRange_eq]

section Facts

variable {n : Nat} {L : Level} {rest : List Level}

local notation "W" => width n
local notation "e" => ident n (width n)

theorem shapeOk_iff : shapeOk n W L = true ↔
    L.base < n ∧ 0 < L.size ∧ L.orbit.get 0 = L.base ∧
    (∀ j < L.size, L.orbit.get j < n ∧ field W L.lookup (L.orbit.get j) = j + 1) ∧
    (∀ x < n, field W L.lookup x = 0 ∨
      (field W L.lookup x ≤ L.size ∧ L.orbit.get (field W L.lookup x - 1) = x)) := by
  simp only [shapeOk, allRange_iff, Bool.and_eq_true, Bool.or_eq_true, blt_eq_decide,
    ble_eq_decide, beq_eq_decide, decide_eq_true_eq, Nat.succ_eq_add_one, sub_eq]
  constructor
  · rintro ⟨⟨⟨⟨h1, h2⟩, h3⟩, h4⟩, h5⟩
    exact ⟨h1, h2, h3, h4, h5⟩
  · rintro ⟨h1, h2, h3, h4, h5⟩
    exact ⟨⟨⟨⟨h1, h2⟩, h3⟩, h4⟩, h5⟩

theorem transversalOk_iff : transversalOk n W e L = true ↔
    L.reps.get 0 = e ∧
    (∀ j < L.size, j ≠ 0 →
      (L.parents.get j).1 < L.gens.length ∧ (L.parents.get j).2 < j ∧
      field W (gen L (L.parents.get j).1) (L.orbit.get (L.parents.get j).2) = L.orbit.get j ∧
      L.reps.get j = comp n W (gen L (L.parents.get j).1) (L.reps.get (L.parents.get j).2)) ∧
    (∀ j < L.size, comp n W (L.invs.get j) (L.reps.get j) = e) := by
  simp only [transversalOk, allRange_iff, Bool.and_eq_true, Bool.or_eq_true, blt_eq_decide,
    beq_eq_decide, decide_eq_true_eq]
  constructor
  · rintro ⟨⟨h1, h2⟩, h3⟩
    refine ⟨h1, fun j hj hj0 => ?_, h3⟩
    rcases h2 j hj with h | ⟨⟨⟨a, b⟩, c⟩, d⟩
    · exact absurd h hj0
    · exact ⟨a, b, c, d⟩
  · rintro ⟨h1, h2, h3⟩
    refine ⟨⟨h1, fun j hj => ?_⟩, h3⟩
    by_cases hj0 : j = 0
    · exact Or.inl hj0
    · obtain ⟨a, b, c, d⟩ := h2 j hj hj0
      exact Or.inr ⟨⟨⟨a, b⟩, c⟩, d⟩

theorem pairsOk_iff (lo hi : Nat) : pairsOk n W e L rest lo hi = true ↔
    ∀ p, lo ≤ p → p < hi →
      field W L.lookup (field W (gen L (p / L.size)) (L.orbit.get (p % L.size))) ≠ 0 ∧
      sift n W e rest (schreier n W L (p / L.size) (p % L.size)) = true := by
  simp only [pairsOk, allRange_iff, Bool.and_eq_true, Bool.not_eq_true', beq_eq_decide,
    decide_eq_false_iff_not, sub_eq, add_eq, div_eq, mod_eq]
  constructor
  · intro h p hlo hhi
    have := h (p - lo) (by omega)
    rwa [show lo + (p - lo) = p by omega] at this
  · intro h t ht
    exact h (lo + t) (by omega) (by omega)

theorem nextOk_iff (nextGens : List Nat) : nextOk n W e L nextGens = true ↔
    L.next.length = nextGens.length ∧
    ∀ q ∈ L.next.zip nextGens, (∀ p ∈ q.1, p.1 < L.gens.length ∧ p.2 < L.size) ∧
      schreierProduct n W e L q.1 = q.2 := by
  simp [nextOk, blt_eq_decide, beq_eq_decide]

end Facts

/-! # The subgroup of a level -/

/-- The permutations represented by the generators of a level. -/
@[expose] def genSet (n : Nat) (L : Level) : (Perm n → Prop) :=
  fun σ => ∃ s ∈ L.gens, Rep n s σ

/-- The subgroup generated by a level's generators. -/
@[expose] def levelGroup (n : Nat) (L : Level) : (Perm n → Prop) :=
  Span (genSet n L)

/-- The subgroup of the first of a list of levels, trivial for no levels. -/
@[expose] def groupOf (n : Nat) : List Level → (Perm n → Prop)
  | [] => Span (fun _ => False)
  | L :: _ => levelGroup n L

private theorem groupOf_id (ls : List Level) : groupOf n ls (Perm.id n) := by
  cases ls <;> exact Span.id

private theorem groupOf_comp (ls : List Level) {p q : Perm n}
    (hp : groupOf n ls p) (hq : groupOf n ls q) : groupOf n ls (p.comp q) := by
  cases ls <;> exact Span.comp hp hq

private theorem groupOf_inv (ls : List Level) {p : Perm n}
    (hp : groupOf n ls p) : groupOf n ls p.inv := by
  cases ls <;> exact Span.inv hp

/-- The inverse of a permutation is one of its powers. -/
theorem inv_eq_pow (σ : Perm n) : σ.inv = σ.pow (σ.order - 1) := by
  have h1 : σ * σ.pow (σ.order - 1) = 1 := by
    have := σ.pow_order
    rw [show σ.order = σ.order - 1 + 1 from (Nat.sub_add_cancel σ.order_pos).symm,
      Perm.pow_succ] at this
    exact this
  exact (inv_unique h1).symm

theorem gen_eq_getElem {L : Level} {i : Nat} (hi : i < L.gens.length) :
    gen L i = L.gens[i] := by
  simp [gen, List.getD_eq_getElem?_getD, hi]

theorem gen_mem {L : Level} {i : Nat} (hi : i < L.gens.length) : gen L i ∈ L.gens := by
  rw [gen_eq_getElem hi]
  exact List.getElem_mem hi

theorem exists_gen_eq {L : Level} {s : Nat} (hs : s ∈ L.gens) :
    ∃ i < L.gens.length, gen L i = s := by
  obtain ⟨i, hi, rfl⟩ := List.getElem_of_mem hs
  exact ⟨i, hi, gen_eq_getElem hi⟩

section Level

variable {n : Nat} {L : Level} {rest : List Level}

local notation "W" => width n
local notation "e" => ident n (width n)

/-- The checks of one level of an accepted certificate, and representatives
for its generators. -/
structure LevelBase (n : Nat) (L : Level) (rest : List Level) : Prop where
  shape : shapeOk n (width n) L = true
  trans : transversalOk n (width n) (ident n (width n)) L = true
  next : nextOk n (width n) (ident n (width n)) L (headGens rest) = true
  pairs : pairsOk n (width n) (ident n (width n)) L rest 0 (L.gens.length * L.size) = true
  gens : ∀ s ∈ L.gens, ∃ σ, Rep n s σ

namespace LevelBase

variable (h : LevelBase n L rest)
include h

theorem base_lt : L.base < n := ((shapeOk_iff.mp h.shape).1)

theorem size_pos : 0 < L.size := (shapeOk_iff.mp h.shape).2.1

theorem orbit_zero : L.orbit.get 0 = L.base := (shapeOk_iff.mp h.shape).2.2.1

theorem orbit_lt {j : Nat} (hj : j < L.size) : L.orbit.get j < n :=
  ((shapeOk_iff.mp h.shape).2.2.2.1 j hj).1

theorem lookup_orbit {j : Nat} (hj : j < L.size) : field W L.lookup (L.orbit.get j) = j + 1 :=
  ((shapeOk_iff.mp h.shape).2.2.2.1 j hj).2

theorem lookup_spec {x : Nat} (hx : x < n) (h0 : field W L.lookup x ≠ 0) :
    field W L.lookup x ≤ L.size ∧ L.orbit.get (field W L.lookup x - 1) = x := by
  rcases (shapeOk_iff.mp h.shape).2.2.2.2 x hx with h' | h'
  · exact absurd h' h0
  · exact h'

/-- The orbit as a set of points. -/
@[expose] def Ω (_ : LevelBase n L rest) : (Fin n → Prop) := fun x => field W L.lookup x.val ≠ 0

/-- The orbit point `j`. -/
def pt (j : Nat) (hj : j < L.size) : Fin n := ⟨L.orbit.get j, h.orbit_lt hj⟩

/-- The orbit index of a point of the orbit. -/
def idx (_ : LevelBase n L rest) (x : Fin n) : Nat := field W L.lookup x.val - 1

theorem idx_lt {x : Fin n} (hx : h.Ω (x)) : h.idx x < L.size := by
  have := (h.lookup_spec x.isLt hx).1
  have h0 : field W L.lookup x.val ≠ 0 := hx
  unfold idx
  omega

theorem pt_idx {x : Fin n} (hx : h.Ω (x)) : h.pt (h.idx x) (h.idx_lt hx) = x :=
  Fin.ext (h.lookup_spec x.isLt hx).2

theorem pt_mem {j : Nat} (hj : j < L.size) : h.Ω (h.pt j hj) := by
  show field W L.lookup (L.orbit.get j) ≠ 0
  rw [h.lookup_orbit hj]
  omega

theorem idx_pt {j : Nat} (hj : j < L.size) : h.idx (h.pt j hj) = j := by
  show field W L.lookup (L.orbit.get j) - 1 = j
  rw [h.lookup_orbit hj]
  omega

theorem pt_zero : h.pt 0 h.size_pos = ⟨L.base, h.base_lt⟩ := Fin.ext h.orbit_zero

/-- The facts checked for one Schreier pair. -/
theorem pair_facts {i j : Nat} (hi : i < L.gens.length) (hj : j < L.size) :
    field W L.lookup (field W (gen L i) (L.orbit.get j)) ≠ 0 ∧
      Kernel.sift n W e rest (schreier n W L i j) = true := by
  have hp := (pairsOk_iff 0 _ |>.mp h.pairs) (i * L.size + j) (by omega)
    (calc i * L.size + j < i * L.size + L.size := by omega
      _ = (i + 1) * L.size := (Nat.succ_mul _ _).symm
      _ ≤ L.gens.length * L.size := Nat.mul_le_mul_right _ hi)
  have hdiv : (i * L.size + j) / L.size = i := by
    rw [Nat.add_comm, Nat.add_mul_div_right _ _ h.size_pos, Nat.div_eq_of_lt hj, Nat.zero_add]
  have hmod : (i * L.size + j) % L.size = j := by
    rw [Nat.add_comm, Nat.add_mul_mod_self_right, Nat.mod_eq_of_lt hj]
  rwa [hdiv, hmod] at hp

theorem gen_maps {σ : Perm n} (hσ : genSet n L (σ)) {x : Fin n} (hx : h.Ω (x)) :
    h.Ω (σ x) := by
  obtain ⟨s, hs, hsσ⟩ := hσ
  obtain ⟨i, hi, rfl⟩ := exists_gen_eq hs
  have hp := h.pair_facts hi (h.idx_lt hx)
  have hx' : L.orbit.get (h.idx x) = x.val := (h.lookup_spec x.isLt hx).2
  show field W L.lookup (σ x).val ≠ 0
  rw [← hsσ x, ← hx']
  exact hp.1

theorem pow_maps {σ : Perm n} (hσ : genSet n L (σ)) (k : Nat) :
    ∀ x, h.Ω x → h.Ω (σ.pow k x) := by
  induction k with
  | zero => intro x hx; simpa using hx
  | succ k ih => intro x hx; simpa using h.gen_maps hσ (ih x hx)

theorem group_maps {σ : Perm n} (hσ : levelGroup n L (σ)) :
    ∀ x, h.Ω x → h.Ω (σ x) := by
  induction hσ using Span.rec with
  | id => intro x hx; simpa using hx
  | @mul_left a b ha hb ih => intro x hx; simpa using h.gen_maps ha (ih x hx)
  | @inv_mul_left a b ha hb ih =>
    intro x hx
    have := h.pow_maps ha (a.order - 1) _ (ih x hx)
    rw [inv_eq_pow a]
    simpa using this

theorem trans_exists : ∀ j (hj : j < L.size), ∃ τ, levelGroup n L τ ∧
    Rep n (L.reps.get j) τ ∧ τ ⟨L.base, h.base_lt⟩ = h.pt j hj := by
  have ht := transversalOk_iff.mp h.trans
  intro j
  induction j using Nat.strongRecOn with
  | _ j ih =>
    intro hj
    by_cases hj0 : j = 0
    · subst hj0
      refine ⟨1, Span.id, ?_, ?_⟩
      · rw [ht.1]; exact rep_ident
      · rw [h.pt_zero]; exact Perm.get_id _
    · obtain ⟨hi, hk, hedge, hrep⟩ := ht.2.1 j hj hj0
      obtain ⟨τ, hτG, hτ, hτb⟩ := ih _ hk (by omega)
      obtain ⟨σ, hσ⟩ := h.gens _ (gen_mem hi)
      refine ⟨σ * τ, Span.comp (Span.generator ⟨_, gen_mem hi, hσ⟩) hτG, ?_, ?_⟩
      · rw [hrep]; exact rep_comp hσ hτ
      · apply Fin.ext
        rw [Perm.mul_def, Perm.get_comp, hτb, ← hσ]
        exact hedge

/-- The transversal element for orbit point `j`. -/
noncomputable def tr (j : Nat) : Perm n :=
  if hj : j < L.size then Classical.choose (h.trans_exists j hj) else 1

theorem tr_spec {j : Nat} (hj : j < L.size) :
    levelGroup n L (h.tr j) ∧ Rep n (L.reps.get j) (h.tr j) ∧
      h.tr j ⟨L.base, h.base_lt⟩ = h.pt j hj := by
  unfold tr
  simp only [hj, ↓reduceDIte]
  exact Classical.choose_spec (h.trans_exists j hj)

theorem tr_mem {j : Nat} (hj : j < L.size) : levelGroup n L (h.tr j) := (h.tr_spec hj).1

theorem tr_apply {j : Nat} (hj : j < L.size) : h.tr j ⟨L.base, h.base_lt⟩ = h.pt j hj :=
  (h.tr_spec hj).2.2

theorem rep_reps {j : Nat} (hj : j < L.size) : Rep n (L.reps.get j) (h.tr j) := (h.tr_spec hj).2.1

theorem rep_invs {j : Nat} (hj : j < L.size) : Rep n (L.invs.get j) (h.tr j)⁻¹ :=
  rep_inv (h.rep_reps hj) ((transversalOk_iff.mp h.trans).2.2 j hj)

theorem tr_zero : h.tr 0 = 1 := by
  have := h.rep_reps h.size_pos
  rw [(transversalOk_iff.mp h.trans).1] at this
  exact this.unique rep_ident

/-- The permutation represented by generator `i`. -/
theorem rep_gen {i : Nat} (hi : i < L.gens.length) : ∃ σ, Rep n (gen L i) σ :=
  h.gens _ (gen_mem hi)

/-- The Schreier element of `σ` at orbit point `j`. -/
noncomputable def schreierElt (σ : Perm n) (j : Nat) (hj : j < L.size) :
    Perm n :=
  (h.tr (h.idx (σ (h.pt j hj))))⁻¹ * σ * h.tr j

theorem rep_schreier {i j : Nat} (hi : i < L.gens.length) (hj : j < L.size)
    {σ : Perm n} (hσ : Rep n (gen L i) σ) :
    Rep n (schreier n W L i j) (h.schreierElt σ j hj) := by
  have hk : field W L.lookup (field W (gen L i) (L.orbit.get j)) - 1 = h.idx (σ (h.pt j hj)) := by
    unfold idx
    rw [← hσ]
    rfl
  have hk' : Nat.sub (field W L.lookup (field W (gen L i) (L.orbit.get j))) 1 =
      h.idx (σ (h.pt j hj)) := hk
  unfold schreier schreierElt
  simp only
  rw [hk', mul_assoc]
  exact rep_comp (h.rep_invs (h.idx_lt (h.gen_maps ⟨_, gen_mem hi, hσ⟩ (h.pt_mem hj))))
    (rep_comp hσ (h.rep_reps hj))

theorem schreierElt_fixes {σ : Perm n} (hσ : ∀ x, h.Ω x → h.Ω (σ x))
    {j : Nat} (hj : j < L.size) :
    h.schreierElt σ j hj ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩ := by
  have hm := hσ _ (h.pt_mem hj)
  unfold schreierElt
  simp only [Perm.mul_def, Perm.inv_def, Perm.get_comp]
  rw [ h.tr_apply hj, inv_eq_iff_eq,
    h.tr_apply (h.idx_lt hm), h.pt_idx hm]

theorem schreierElt_mem {σ : Perm n} (hσ : levelGroup n L (σ))
    {j : Nat} (hj : j < L.size) : levelGroup n L (h.schreierElt σ j hj) := by
  have hm := h.group_maps hσ _ (h.pt_mem hj)
  exact Span.comp (Span.comp (Span.inv (h.tr_mem (h.idx_lt hm))) hσ) (h.tr_mem hj)

/-- A product of Schreier generators of this level fixes the base point and
lies in the level's group. -/
theorem schreierProduct_spec : ∀ (qs : List (Nat × Nat)),
    (∀ p ∈ qs, p.1 < L.gens.length ∧ p.2 < L.size) →
    ∃ τ, Rep n (schreierProduct n W e L qs) τ ∧ levelGroup n L (τ) ∧
      τ ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩
  | [], _ => ⟨1, rep_ident, Span.id, by simp [Perm.one_def]⟩
  | q :: qs, hq => by
    obtain ⟨hi, hj⟩ := hq q List.mem_cons_self
    obtain ⟨τ, hτ, hτG, hτb⟩ := schreierProduct_spec qs fun p hp => hq p (List.mem_cons_of_mem _ hp)
    obtain ⟨σ, hσ⟩ := h.rep_gen hi
    have hσG : levelGroup n L (σ) := Span.generator ⟨_, gen_mem hi, hσ⟩
    refine ⟨h.schreierElt σ _ hj * τ, rep_comp (h.rep_schreier hi hj hσ) hτ,
      Span.comp (h.schreierElt_mem hσG hj) hτG, ?_⟩
    simp only [Perm.mul_def, Perm.get_comp, hτb]
    exact h.schreierElt_fixes (h.group_maps hσG) hj

/-- The next level's generators are products of Schreier elements of this level. -/
theorem next_gens {L' : Level} {rest' : List Level} (hrest : rest = L' :: rest')
    {t : Nat} (ht : t ∈ L'.gens) :
    ∃ τ, Rep n t τ ∧ levelGroup n L (τ) ∧ τ ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩ := by
  subst hrest
  obtain ⟨hlen, hall⟩ := (nextOk_iff _).mp h.next
  simp only [headGens] at hlen hall
  obtain ⟨m, hm, rfl⟩ := List.getElem_of_mem ht
  have hq : (L.next[m]'(by omega), L'.gens[m]) ∈ L.next.zip L'.gens :=
    List.mem_iff_getElem.mpr ⟨m, by simp [List.length_zip]; omega, by simp [List.getElem_zip]⟩
  obtain ⟨hidx, hs⟩ := hall _ hq
  simp only at hs
  rw [← hs]
  exact h.schreierProduct_spec _ hidx

end LevelBase

/-- The checks of one level together with the soundness of sifting through the
levels after it. -/
structure LevelHyp (n : Nat) (L : Level) (rest : List Level) : Prop
    extends LevelBase n L rest where
  sift : ∀ x σ, Rep n x σ → Canon n x →
    (sift n (width n) (ident n (width n)) rest x = true ↔ groupOf n rest (σ))

namespace LevelHyp

variable (h : LevelHyp n L rest)
include h

theorem gen_schreier_mem {σ : Perm n} (hσ : genSet n L (σ))
    {j : Nat} (hj : j < L.size) : groupOf n rest (h.schreierElt σ j hj) := by
  obtain ⟨s, hs, hsσ⟩ := hσ
  obtain ⟨i, hi, rfl⟩ := exists_gen_eq hs
  exact (h.sift _ _ (h.rep_schreier hi hj hsσ) (canon_comp _ _)).mp (h.pair_facts hi hj).2

/-- One generator step of Schreier's lemma. -/
theorem schreier_step {a b : Perm n} (ha : genSet n L (a)) (hb : levelGroup n L (b))
    (ih : ∀ j (hj : j < L.size), groupOf n rest (h.schreierElt b j hj)) :
    ∀ j (hj : j < L.size), groupOf n rest (h.schreierElt (a.comp b) j hj) := by
  intro j hj
  have hm := h.group_maps hb _ (h.pt_mem hj)
  have hk := h.idx_lt hm
  have := groupOf_comp rest (h.gen_schreier_mem ha hk) (ih j hj)
  unfold LevelBase.schreierElt at this ⊢
  rw [h.pt_idx hm] at this
  simpa [Perm.comp_assoc] using this

theorem schreier_pow {a b : Perm n} (ha : genSet n L (a)) (hb : levelGroup n L (b))
    (ih : ∀ j (hj : j < L.size), groupOf n rest (h.schreierElt b j hj)) (k : Nat) :
    levelGroup n L ((a.pow k).comp b) ∧
      ∀ j (hj : j < L.size), groupOf n rest (h.schreierElt ((a.pow k).comp b) j hj) := by
  induction k with
  | zero => simpa using ⟨hb, ih⟩
  | succ k ihk =>
    rw [Perm.pow_succ, Perm.comp_assoc]
    exact ⟨Span.mul_left ha ihk.1, h.schreier_step ha ihk.1 ihk.2⟩

/-- Schreier's lemma for the certified transversal. -/
theorem schreier_mem {σ : Perm n} (hσ : levelGroup n L (σ)) :
    ∀ j (hj : j < L.size), groupOf n rest (h.schreierElt σ j hj) := by
  induction hσ using Span.rec with
  | id =>
    intro j hj
    unfold LevelBase.schreierElt
    simp only [Perm.get_id, h.idx_pt hj, Perm.mul_def, Perm.inv_def, Perm.comp_id, Perm.inv_comp_self]
    exact groupOf_id rest
  | @mul_left a b ha hb ih => exact h.schreier_step ha hb ih
  | @inv_mul_left a b ha hb ih =>
    rw [inv_eq_pow a]
    exact (h.schreier_pow ha hb ih (a.order - 1)).2

theorem mem_rest_of_fixes {σ : Perm n} (hσ : levelGroup n L (σ))
    (hb : σ ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩) : groupOf n rest (σ) := by
  have := h.schreier_mem hσ 0 h.size_pos
  unfold LevelBase.schreierElt at this
  rw [h.pt_zero, hb, ← h.pt_zero, h.idx_pt, h.tr_zero, inv_one, one_mul, mul_one] at this
  exact this

theorem rest_le {σ : Perm n} (hσ : groupOf n rest (σ)) :
    levelGroup n L (σ) ∧ σ ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩ := by
  match hr : rest with
  | [] =>
    have hσ := Span.empty.mp hσ
    subst σ
    exact ⟨Span.id, Perm.get_id _⟩
  | L' :: rest' =>
    apply Span.lift (P := fun τ => levelGroup n L (τ) ∧
      τ ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩) ?_ ?_ ?_ ?_ hσ
    · exact ⟨Span.id, Perm.get_id _⟩
    · rintro τ ⟨t, ht, htτ⟩
      obtain ⟨τ', hτ', hG, hb⟩ := h.next_gens rfl ht
      rw [htτ.unique hτ']
      exact ⟨hG, hb⟩
    · intro p q hp hq
      exact ⟨Span.comp hp.1 hq.1, by simp [Perm.get_comp, hp.2, hq.2]⟩
    · intro p hp
      refine ⟨Span.inv hp.1, ?_⟩
      apply p.get_inj
      simp [hp.2]

theorem mem_rest_iff {σ : Perm n} : groupOf n rest (σ) ↔
    levelGroup n L (σ) ∧ σ ⟨L.base, h.base_lt⟩ = ⟨L.base, h.base_lt⟩ := by
  constructor
  · intro hσ
    exact ⟨(h.rest_le hσ).1, (h.rest_le hσ).2⟩
  · rintro ⟨hσ, hb⟩
    exact h.mem_rest_of_fixes hσ hb

theorem base_mem : h.Ω ((⟨L.base, h.base_lt⟩ : Fin n)) := by
  rw [← h.pt_zero]
  exact h.pt_mem _

/-- Sifting from this level accepts exactly the packings of its subgroup. -/
theorem sift_iff {x : Nat} {σ : Perm n} (hx : Rep n x σ) :
    Kernel.sift n W e (L :: rest) x = true ↔ levelGroup n L (σ) := by
  have hxb : field W x L.base = (σ ⟨L.base, h.base_lt⟩).val := hx ⟨L.base, h.base_lt⟩
  by_cases he : x = e
  · subst x
    have hσ : σ = 1 := hx.unique rep_ident
    subst σ
    simp only [Kernel.sift, Nat.beq_refl, Bool.cond_true, true_iff]
    exact Span.id
  have hne : Nat.beq x e = false := by
    simpa [beq_eq_decide] using he
  simp only [Kernel.sift, hne, Bool.cond_false, hxb]
  by_cases hΩ : h.Ω (σ ⟨L.base, h.base_lt⟩)
  · have h0 : field W L.lookup (σ ⟨L.base, h.base_lt⟩).val ≠ 0 := hΩ
    have hk := h.idx_lt hΩ
    rw [show Nat.beq (field W L.lookup (σ ⟨L.base, h.base_lt⟩).val) 0 = false by
      simpa [beq_eq_decide] using h0, Bool.cond_false]
    have hk' : Nat.sub (field W L.lookup (σ ⟨L.base, h.base_lt⟩).val) 1 =
        h.idx (σ ⟨L.base, h.base_lt⟩) := rfl
    rw [hk', h.sift _ _ (rep_comp (h.rep_invs hk) hx) (canon_comp _ _), h.mem_rest_iff]
    constructor
    · rintro ⟨hG, _⟩
      have := Span.comp (h.tr_mem hk) hG
      simpa [levelGroup, ← Perm.comp_assoc] using this
    · intro hσ
      refine ⟨Span.comp (Span.inv (h.tr_mem hk)) hσ, ?_⟩
      simp only [Perm.mul_def, Perm.inv_def, Perm.get_comp]
      rw [inv_eq_iff_eq, h.tr_apply hk, h.pt_idx hΩ]
  · have h0 : field W L.lookup (σ ⟨L.base, h.base_lt⟩).val = 0 := by
      exact Decidable.byContradiction fun hne => hΩ hne
    rw [h0]
    simp only [Nat.beq_refl, Bool.cond_true, Bool.false_eq_true, false_iff]
    intro hσ
    exact hΩ (h.group_maps hσ _ h.base_mem)

/-- The certified transversal decomposes each generated permutation uniquely
into its orbit index and a permutation in the point stabilizer. -/
noncomputable def decompose :
    Bijection {p : Perm n // levelGroup n L p}
      (Fin L.size × {p : Perm n // groupOf n rest p}) where
  toFun p :=
    let hm := h.group_maps p.property _ h.base_mem
    let j := h.idx (p.val.get ⟨L.base, h.base_lt⟩)
    let hj := h.idx_lt hm
    (⟨j, hj⟩, ⟨(h.tr j).inv.comp p.val, h.mem_rest_iff.mpr
      ⟨Span.comp (Span.inv (h.tr_mem hj)) p.property, by
        apply (h.tr j).get_inj
        simp only [Perm.get_comp, Perm.get_inv_get]
        rw [h.tr_apply hj, h.pt_idx hm]⟩⟩)
  invFun x := ⟨(h.tr x.1.val).comp x.2.val,
    Span.comp (h.tr_mem x.1.isLt) (h.rest_le x.2.property).1⟩
  left_inv p := by
    apply Subtype.ext
    simp
  right_inv x := by
    have hb := (h.rest_le x.2.property).2
    have hj : h.idx (((h.tr x.1.val).comp x.2.val).get ⟨L.base, h.base_lt⟩) = x.1.val := by
      rw [Perm.get_comp, hb, h.tr_apply x.1.isLt, h.idx_pt x.1.isLt]
    apply Prod.ext
    · exact Fin.ext hj
    · apply Subtype.ext
      simp only [hj]
      simp

end LevelHyp

end Level

/-! # The whole certificate -/

section Sound

variable {n : Nat}

local notation "W" => width n
local notation "e" => ident n (width n)

theorem levelsOk_cons {L : Level} {rest : List Level} :
    levelsOk n W e (L :: rest) = true ↔
      (shapeOk n W L = true ∧ transversalOk n W e L = true ∧
        nextOk n W e L (headGens rest) = true) ∧
      pairsOk n W e L rest 0 (L.gens.length * L.size) = true ∧ levelsOk n W e rest = true := by
  simp only [levelsOk, levelOk, Bool.and_eq_true, mul_eq, and_assoc]

theorem order_cons (L : Level) (rest : List Level) : order (L :: rest) = L.size * order rest := rfl

/-- Soundness of sifting and the mixed-radix enumeration, from the last level upward. -/
theorem levels_sound : ∀ ls : List Level, levelsOk n W e ls = true →
    (∀ s ∈ headGens ls, ∃ σ, Rep n s σ) →
    (∀ x σ, Rep n x σ → Canon n x → (Kernel.sift n W e ls x = true ↔ groupOf n ls σ)) ∧
      Nonempty (Bijection {p : Perm n // groupOf n ls p} (Fin (order ls)))
  | [], _, _ => by
    refine ⟨fun x σ hx hc => ?_, ⟨?_, ?_, ?_, ?_⟩⟩
    · simp only [Kernel.sift, groupOf, Span.empty, beq_eq_decide, decide_eq_true_eq]
      constructor
      · rintro rfl
        exact hx.unique rep_ident
      · rintro rfl
        exact hc.eq_of_rep canon_ident hx rep_ident
    · exact fun _ => ⟨0, by decide⟩
    · exact fun _ => ⟨Perm.id n, Span.id⟩
    · intro p
      apply Subtype.ext
      exact (Span.empty.mp p.property).symm
    · intro k
      apply Fin.ext
      have := k.isLt
      change k.val < 1 at this
      change 0 = k.val
      omega
  | L :: rest, hok, hgens => by
    obtain ⟨⟨hs, ht, hn⟩, hp, hrest⟩ := levelsOk_cons.mp hok
    have base : LevelBase n L rest := ⟨hs, ht, hn, hp, hgens⟩
    have hgens' : ∀ s ∈ headGens rest, ∃ σ, Rep n s σ := by
      match hr : rest with
      | [] => simp [headGens]
      | L' :: rest' =>
        intro t htt
        obtain ⟨τ, hτ, -⟩ := base.next_gens rfl htt
        exact ⟨τ, hτ⟩
    obtain ⟨ih₁, ⟨ih₂⟩⟩ := levels_sound rest hrest hgens'
    have hyp : LevelHyp n L rest := { base with sift := ih₁ }
    exact ⟨fun x σ hx _ => hyp.sift_iff hx,
      ⟨hyp.decompose.trans ((Bijection.refl _).prod ih₂) |>.trans (Bijection.finMul _ _)⟩⟩

theorem check_iff (inputs : List Nat) (c : Certificate) : check n inputs c = true ↔
    inputsOk n W e inputs c = true ∧ levelsOk n W e c = true := by
  simp [check]

private theorem input_reps {S : Array (Perm n)} {c : Certificate}
    (hin : inputsOk n W e (S.toList.map pack) c = true) :
    ∀ s ∈ headGens c, ∃ σ, Rep n s σ ∧ Generated S σ := by
  simp only [inputsOk, Bool.and_eq_true, List.all_eq_true, List.any_eq_true, List.mem_map,
    Bool.or_eq_true, beq_eq_decide, decide_eq_true_eq] at hin
  intro s hs
  obtain ⟨x, ⟨p, hpS, rfl⟩, hx⟩ := hin.2 s hs
  have hpc : Generated S p := .generator (Array.mem_toList_iff.mp hpS)
  rcases hx with rfl | hx
  · exact ⟨_, rep_pack p, hpc⟩
  · exact ⟨_, rep_inv (rep_pack p) hx, .inv hpc⟩

/-- The first level of an accepted certificate generates exactly the inputs. -/
theorem groupOf_iff_generated {S : Array (Perm n)} {c : Certificate}
    (h : check n (S.toList.map pack) c = true) (p : Perm n) :
    groupOf n c p ↔ Generated S p := by
  obtain ⟨hin, hlv⟩ := (check_iff _ _).mp h
  have hgens := input_reps hin
  have hsound := levels_sound c hlv fun s hs => (hgens s hs).imp fun _ h => h.1
  constructor
  · intro hp
    match hc : c with
    | [] =>
      have he := Span.empty.mp hp
      rw [he]
      exact .id
    | L :: _ =>
      apply Span.lift (P := Generated S) .id ?_ (fun _ _ => .comp) (fun _ => .inv) hp
      rintro σ ⟨s, hs, hsσ⟩
      obtain ⟨τ, hτ, hτS⟩ := hgens s hs
      rwa [hsσ.unique hτ]
  · intro hp
    apply hp.lift (groupOf_id c) ?_ (fun _ _ => groupOf_comp c) (fun _ => groupOf_inv c)
    intro q hq
    apply (hsound.1 _ _ (rep_pack q) (canon_pack q)).mp
    simp only [inputsOk, Bool.and_eq_true, List.all_eq_true] at hin
    exact hin.1 _ (List.mem_map.mpr ⟨q, Array.mem_toList_iff.mpr hq, rfl⟩)

/-- An accepted certificate decides generation for every Hex permutation. -/
theorem sift_pack_iff {S : Array (Perm n)} {c : Certificate}
    (h : check n (S.toList.map pack) c = true) (p : Perm n) :
    Kernel.sift n W e c (pack p) = true ↔ Generated S p := by
  obtain ⟨hin, hlv⟩ := (check_iff _ _).mp h
  exact ((levels_sound c hlv (fun s hs => (input_reps hin s hs).imp fun _ h => h.1)).1
    _ _ (rep_pack p) (canon_pack p)).trans (groupOf_iff_generated h p)

/-- An accepted certificate enumerates exactly the generated permutations. -/
theorem order_of_check {S : Array (Perm n)} {c : Certificate}
    (h : check n (S.toList.map pack) c = true) : HasOrder S (order c) := by
  obtain ⟨hin, hlv⟩ := (check_iff _ _).mp h
  obtain ⟨f⟩ := (levels_sound c hlv
    (fun s hs => (input_reps hin s hs).imp fun _ h => h.1)).2
  let g : Bijection {p : Perm n // Generated S p} {p : Perm n // groupOf n c p} :=
    ⟨fun p => ⟨p.val, (groupOf_iff_generated h p.val).mpr p.property⟩,
      fun p => ⟨p.val, (groupOf_iff_generated h p.val).mp p.property⟩,
      fun _ => rfl, fun _ => rfl⟩
  unfold HasOrder
  exact ⟨g.trans f⟩

end Sound

end Hex.PermGroup.Kernel
