/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Normal.Commutator

public section

namespace Hex.PermGroup.Derived

/-- The subgroup generated by commutators of all ambient elements. -/
inductive Member (G : Group n) : Perm n → Prop
  | id : Member G (Perm.id n)
  | comm {p q} : Generated G.generators p → Generated G.generators q → Member G (p.comm q)
  | comp {p q} : Member G p → Member G q → Member G (p.comp q)
  | inv {p} : Member G p → Member G p.inv

theorem Member.conj {G : Group n} {p g : Perm n} (hp : Member G p)
    (hg : Generated G.generators g) : Member G (g.conj p) := by
  induction hp with
  | id => simpa using (Member.id (G := G))
  | @comm p q hp hq =>
    rw [Perm.conj_comm]
    exact .comm (hg.comp (hp.comp hg.inv)) (hg.comp (hq.comp hg.inv))
  | comp _ _ ip iq => simpa only [Perm.conj_comp] using ip.comp iq
  | inv _ ip => simpa only [Perm.conj_inv] using ip.inv

/-- Original generator-pair commutators in first-occurrence order, omitting
identities and duplicates. Removing this redundancy prevents repeated squaring
of the presentation size in a derived series. -/
@[expose] def seeds (G : Group n) : Array (Perm n) :=
  (((G.generators.flatMap fun p => G.generators.map p.comm).filter
    fun p => p != Perm.id n).toList.eraseDups).toArray

theorem mem_seeds (G : Group n) (r : Perm n) : r ∈ seeds G ↔
    (∃ p ∈ G.generators, ∃ q ∈ G.generators, p.comm q = r) ∧ r ≠ Perm.id n := by
  simp [seeds]

@[expose] def seedGroup (G : Group n) : Group n := Group.ofGenerators (seeds G)

theorem seed_comm (G : Group n) (p : Perm n) (hp : p ∈ G.generators)
    (q : Perm n) (hq : q ∈ G.generators) : Generated (seedGroup G).generators (p.comm q) := by
  by_cases he : p.comm q = Perm.id n
  · rw [he]; exact .id
  · exact .generator ((mem_seeds G _).mpr ⟨⟨p, hp, q, hq, rfl⟩, he⟩)

theorem seed_inside (G : Group n) : (seedGroup G).IsSubgroup G := by
  intro p hp
  apply hp.mono
  intro r hr
  obtain ⟨⟨p, hp, q, hq, rfl⟩, _⟩ := (mem_seeds G r).mp hr
  exact (Generated.generator hp).comp ((Generated.generator hq).comp
    ((Generated.generator hp).inv.comp (Generated.generator hq).inv))

theorem seed_member (G : Group n) (p : Perm n) (hp : Generated (seedGroup G).generators p) : Member G p := by
  apply hp.lift .id ?_ (fun _ _ => .comp) (fun _ => .inv)
  intro r hr
  obtain ⟨⟨p, hp, q, hq, rfl⟩, _⟩ := (mem_seeds G r).mp hr
  exact .comm (.generator hp) (.generator hq)

end Hex.PermGroup.Derived

namespace Hex.PermGroup.Group

/-- A complete normal-closure trace starting from original generator-pair
commutators. The trace proves that no extra elements were introduced. -/
@[expose] def derivedCert (G : Group n) : Normal.Closure G (Derived.seedGroup G) :=
  G.normalClosureCert (Derived.seedGroup G) (Derived.seed_inside G)

@[expose] def derived (G : Group n) : Group n := G.derivedCert.group

theorem derived_inside (G : Group n) : G.derived.IsSubgroup G := G.derivedCert.inside (Derived.seed_inside G)

theorem derived_normal (G : Group n) : G.derived.isNormal G G.derived_inside = true :=
  (Normal.check_normal G G.derived G.derived_inside).mp G.derivedCert.normal

theorem generator_comm_mem (G : Group n) (p : Perm n) (hp : p ∈ G.generators)
    (q : Perm n) (hq : q ∈ G.generators) : Generated G.derived.generators (p.comm q) :=
  G.derivedCert.contains _ (Derived.seed_comm G p hp q hq)

theorem comm_mem_derived (G : Group n) (p q : Perm n)
    (hp : Generated G.generators p) (hq : Generated G.generators q) :
    Generated G.derived.generators (p.comm q) :=
  Normal.comm_generated G G.derived G.derivedCert.normal G.generator_comm_mem p q hp hq

/-- The finite generator construction equals the subgroup generated by all
element commutators, in both directions. -/
theorem mem_derived (G : Group n) (p : Perm n) :
    Generated G.derived.generators p ↔ Derived.Member G p := by
  constructor
  · exact Normal.replay_lift G.derivedCert.replayed .id (fun _ _ => .comp) (fun _ => .inv)
      (fun _ _ hg hp => hp.conj hg) (Derived.seed_member G) p
  · intro hp
    induction hp with
    | id => exact .id
    | comm hp hq => exact G.comm_mem_derived _ _ hp hq
    | comp _ _ ip iq => exact ip.comp iq
    | inv _ ip => exact ip.inv

/-- The derived subgroup is the least subgroup containing all commutators;
the candidate subgroup need not be assumed normal. -/
theorem derived_le (G N : Group n) : G.derived.IsSubgroup N ↔
    ∀ p q, Generated G.generators p → Generated G.generators q → Generated N.generators (p.comm q) := by
  constructor
  · exact fun h p q hp hq => h _ (G.comm_mem_derived p q hp hq)
  · intro h p hp
    have hm := (G.mem_derived p).mp hp
    clear hp
    induction hm with
    | id => exact .id
    | comm hp hq => exact h _ _ hp hq
    | comp _ _ ip iq => exact ip.comp iq
    | inv _ ip => exact ip.inv

theorem IsSubgroup.derived {G H : Group n} (h : H.IsSubgroup G) : H.derived.IsSubgroup G.derived :=
  (H.derived_le G.derived).mpr fun p q hp hq => G.comm_mem_derived p q (h p hp) (h q hq)

end Hex.PermGroup.Group
