/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Perm

public section

namespace Hex.PermGroup

/-- Membership in the subgroup generated by the original input array. -/
inductive Generated {n : Nat} (S : Array (Perm n)) : Perm n → Prop
  | id : Generated S (Perm.id n)
  | generator {p} : p ∈ S → Generated S p
  | comp {p q} : Generated S p → Generated S q → Generated S (p.comp q)
  | inv {p} : Generated S p → Generated S p.inv

namespace Generated

/-- A predicate closed under the group operations contains the generated subgroup
whenever it contains the input generators. -/
theorem lift {S : Array (Perm n)} {P : Perm n → Prop}
    (hi : P (Perm.id n)) (hs : ∀ p ∈ S, P p)
    (hc : ∀ p q, P p → P q → P (p.comp q))
    (hv : ∀ p, P p → P p.inv) {p} (h : Generated S p) : P p := by
  induction h with
  | id => exact hi
  | generator h => exact hs _ h
  | comp _ _ hp hq => exact hc _ _ hp hq
  | inv _ hp => exact hv _ hp

/-- Replacing each generator by a word in another array preserves membership. -/
theorem mono {S T : Array (Perm n)} (h : ∀ p ∈ S, Generated T p)
    {p} (hp : Generated S p) : Generated T p :=
  hp.lift .id h (fun _ _ => .comp) (fun _ => .inv)

end Generated

/-- Every permutation of the declared degree is generated by `S`. -/
@[expose] def GeneratesAll (S : Array (Perm n)) : Prop := ∀ p, Generated S p

end Hex.PermGroup
