/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Generated

public section

namespace Hex.PermGroup

/-- Mutually inverse maps, without a dependency on Mathlib's `Equiv`. -/
structure Bijection (α β : Type) where
  /-- The forward map. -/
  toFun : α → β
  /-- The inverse map. -/
  invFun : β → α
  /-- Inverting the forward map recovers its input. -/
  left_inv : ∀ x, invFun (toFun x) = x
  /-- Applying the forward map after its inverse recovers its input. -/
  right_inv : ∀ y, toFun (invFun y) = y

namespace Bijection

def refl (α : Type) : Bijection α α := ⟨id, id, fun _ => rfl, fun _ => rfl⟩

def trans (f : Bijection α β) (g : Bijection β γ) : Bijection α γ :=
  ⟨fun x => g.toFun (f.toFun x), fun z => f.invFun (g.invFun z),
    fun x => by simp [g.left_inv, f.left_inv],
    fun z => by simp [f.right_inv, g.right_inv]⟩

def prod (f : Bijection α β) (g : Bijection γ δ) : Bijection (α × γ) (β × δ) :=
  ⟨fun x => (f.toFun x.1, g.toFun x.2), fun y => (f.invFun y.1, g.invFun y.2),
    fun x => by simp [f.left_inv, g.left_inv],
    fun y => by simp [f.right_inv, g.right_inv]⟩

/-- Mixed-radix encoding of a pair of finite indices. -/
def finMul (a b : Nat) : Bijection (Fin a × Fin b) (Fin (a * b)) where
  toFun x := ⟨x.1.val * b + x.2.val, by
    have := Nat.mul_le_mul_right b x.1.isLt
    rw [Nat.succ_mul] at this
    omega⟩
  invFun k :=
    have hb : 0 < b := by
      have := k.isLt
      by_cases h : b = 0
      · simp [h] at this
      · omega
    (⟨k.val / b, (Nat.div_lt_iff_lt_mul hb).mpr k.isLt⟩,
      ⟨k.val % b, Nat.mod_lt _ hb⟩)
  left_inv x := by
    apply Prod.ext
    · apply Fin.ext
      change (x.1.val * b + x.2.val) / b = x.1.val
      rw [Nat.mul_comm x.1.val, Nat.mul_add_div x.2.pos,
        Nat.div_eq_of_lt x.2.isLt, Nat.add_zero]
    · apply Fin.ext
      change (x.1.val * b + x.2.val) % b = x.2.val
      simp [Nat.add_mod, Nat.mod_eq_of_lt x.2.isLt]
  right_inv k := by
    apply Fin.ext
    simpa only [Nat.mul_comm] using Nat.div_add_mod k.val b

end Bijection

/-- The subgroup generated by `S` has exactly `N` elements: its elements admit
mutually inverse ranking and unranking maps to `Fin N`. -/
@[expose] def HasOrder (S : Array (Perm n)) (N : Nat) : Prop :=
  Nonempty (Bijection {p : Perm n // Generated S p} (Fin N))

end Hex.PermGroup
