/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Perm

public section

namespace Hex.PermGroup

/-- Membership in the subgroup generated by the original input array. -/
inductive Generated {n : Nat} (S : Array (Perm n)) : Perm n → Prop
  | id : Generated S (Perm.id n)
  | generator {p} : p ∈ S → Generated S p
  | comp {p q} : Generated S p → Generated S q → Generated S (p.comp q)
  | inv {p} : Generated S p → Generated S p.inv

namespace Generated

/-- A predicate closed under the group operations contains the generated subgroup
whenever it contains the input generators. -/
theorem lift {S : Array (Perm n)} {P : Perm n → Prop}
    (hi : P (Perm.id n)) (hs : ∀ p ∈ S, P p)
    (hc : ∀ p q, P p → P q → P (p.comp q))
    (hv : ∀ p, P p → P p.inv) {p} (h : Generated S p) : P p := by
  induction h with
  | id => exact hi
  | generator h => exact hs _ h
  | comp _ _ hp hq => exact hc _ _ hp hq
  | inv _ hp => exact hv _ hp

/-- Replacing each generator by a word in another array preserves membership. -/
theorem mono {S T : Array (Perm n)} (h : ∀ p ∈ S, Generated T p)
    {p} (hp : Generated S p) : Generated T p :=
  hp.lift .id h (fun _ _ => .comp) (fun _ => .inv)

end Generated

/-- A word in signed original-generator indices. `true` denotes an inverse. -/
abbrev Word (S : Array (Perm n)) := List (Fin S.size × Bool)

namespace Word

@[expose] def letter (S : Array (Perm n)) (a : Fin S.size × Bool) : Perm n :=
  if a.2 then S[a.1.val].inv else S[a.1.val]

/-- Words use left-action composition: the rightmost letter acts first. -/
@[expose] def eval (S : Array (Perm n)) : Word S → Perm n
  | [] => Perm.id n
  | a :: w => (letter S a).comp (eval S w)

@[simp] theorem eval_nil (S : Array (Perm n)) : eval S [] = Perm.id n := rfl

@[simp] theorem eval_cons (S : Array (Perm n)) (a) (w : Word S) :
    eval S (a :: w) = (letter S a).comp (eval S w) := rfl

theorem eval_append (S : Array (Perm n)) (u v : Word S) :
    eval S (u ++ v) = (eval S u).comp (eval S v) := by
  induction u with
  | nil => simp [eval]
  | cons a u ih => simp [eval, ih, Perm.comp_assoc]

/-- Invert a word by reversing its letters and changing their signs. -/
@[expose] def inv {S : Array (Perm n)} (w : Word S) : Word S :=
  w.reverse.map fun a => (a.1, !a.2)

@[simp] theorem letter_inv (S : Array (Perm n)) (a : Fin S.size × Bool) :
    letter S (a.1, !a.2) = (letter S a).inv := by
  rcases a with ⟨i, b⟩
  cases b <;> simp [letter]

theorem eval_inv (S : Array (Perm n)) (w : Word S) :
    eval S w.inv = (eval S w).inv := by
  induction w with
  | nil => simp [inv, eval]
  | cons a w ih =>
    simp only [inv, List.reverse_cons, List.map_append, List.map_cons, List.map_nil,
      eval_append, eval_cons, eval_nil, Perm.comp_id, letter_inv, Perm.inv_comp]
    exact congrArg (fun p => p.comp (letter S a).inv) ih

theorem eval_generated (S : Array (Perm n)) (w : Word S) : Generated S (eval S w) := by
  induction w with
  | nil => exact .id
  | cons a w ih =>
    apply Generated.comp _ ih
    rcases a with ⟨i, b⟩
    cases b
    · exact .generator (Array.getElem_mem i.isLt)
    · exact .inv (.generator (Array.getElem_mem i.isLt))

end Word

/-- The closure predicate is exactly evaluation of finite signed words. -/
theorem generated_iff_word {S : Array (Perm n)} {p : Perm n} :
    Generated S p ↔ ∃ w : Word S, Word.eval S w = p := by
  constructor
  · intro h
    induction h with
    | id => exact ⟨[], rfl⟩
    | generator h =>
      rcases Array.mem_iff_getElem.mp h with ⟨i, hi, hp⟩
      exact ⟨[(⟨i, hi⟩, false)], by simp [Word.eval, Word.letter, hp]⟩
    | comp _ _ hp hq =>
      rcases hp with ⟨u, hu⟩
      rcases hq with ⟨v, hv⟩
      exact ⟨u ++ v, by rw [Word.eval_append, hu, hv]⟩
    | inv _ hp =>
      rcases hp with ⟨w, hw⟩
      exact ⟨w.inv, by rw [Word.eval_inv, hw]⟩
  · rintro ⟨w, rfl⟩
    exact Word.eval_generated S w

/-- One node in a straight-line program. References address earlier nodes only. -/
inductive Node where
  | id
  | generator (index : Nat)
  | inv (index : Nat)
  | comp (left right : Nat)
  deriving DecidableEq, Repr

/-- Raw program data. Evaluation rejects an invalid node, even if unreachable
from the root, and rejects an out-of-range root. -/
structure Program where
  nodes : Array Node
  root : Nat
  deriving DecidableEq, Repr

namespace Program

/-- Evaluate one node against the already evaluated values. Its result carries
provenance, which is erased by compilation. -/
@[expose] def evalNode (S : Array (Perm n))
    (values : Array {p : Perm n // Generated S p}) :
    Node → Option {p : Perm n // Generated S p}
  | .id => some ⟨Perm.id n, .id⟩
  | .generator i =>
    if h : i < S.size then some ⟨S[i], .generator (Array.getElem_mem h)⟩ else none
  | .inv i => do
    let p ← values[i]?
    return ⟨p.val.inv, .inv p.property⟩
  | .comp i j => do
    let p ← values[i]?
    let q ← values[j]?
    return ⟨p.val.comp q.val, .comp p.property q.property⟩

/-- Check every node in order, using only the values for references. -/
@[expose] def evalNodes (S : Array (Perm n)) :
    List Node → Array {p : Perm n // Generated S p} →
      Option (Array {p : Perm n // Generated S p})
  | [], values => some values
  | node :: rest, values => do
    let p ← evalNode S values node
    evalNodes S rest (values.push p)

/-- Evaluate the root of a fully checked program. -/
@[expose] def evalCertified (S : Array (Perm n)) (program : Program) :
    Option {p : Perm n // Generated S p} := do
  let values ← evalNodes S program.nodes.toList #[]
  values[program.root]?

/-- The executable permutation denoted by a program, or failure for malformed
references or generator indices. -/
@[expose] def eval (S : Array (Perm n)) (program : Program) : Option (Perm n) :=
  (evalCertified S program).map Subtype.val

theorem eval_sound {S : Array (Perm n)} {program : Program} {p : Perm n}
    (h : eval S program = some p) : Generated S p := by
  unfold eval at h
  cases he : evalCertified S program with
  | none => simp [he] at h
  | some q =>
    simp only [he, Option.map_some, Option.some.injEq] at h
    exact h ▸ q.property

end Program

/-- Check that a program in the original generators denotes the claimed element. -/
@[expose] def checkWord (S : Array (Perm n)) (p : Perm n) (program : Program) : Bool :=
  decide (program.eval S = some p)

theorem checkWord_sound {S : Array (Perm n)} {p : Perm n} {program : Program}
    (h : checkWord S p program = true) : Generated S p :=
  Program.eval_sound (of_decide_eq_true h)

end Hex.PermGroup
