/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexPermGroup.Search.Check

public section

namespace Hex.PermGroup.Search

/-- The checked subgroup generated by successful leaves visited so far. -/
structure Accumulator (G : Group n) (P : Predicate n) where
  group : Group n
  inside : group.IsSubgroup G
  satisfies : ∀ p, Generated group.generators p → P.test p = true

namespace Accumulator

variable {G : Group n} {P : Predicate n}

@[expose] def empty (G : Group n) (P : Predicate n) : Accumulator G P where
  group := Group.ofGenerators #[]
  inside := by
    intro p hp
    apply hp.mono
    simp
  satisfies := by
    intro p hp
    exact P.generated (S := #[]) (fun i => Fin.elim0 i) hp

/-- Add a successful leaf and rebuild its checked chain. The traversal calls
this only after the subtree-containment check has failed. -/
@[expose] def adjoin (a : Accumulator G P) (p : Element G) (hp : P.test p.val = true) :
    Accumulator G P where
  group := Group.ofGenerators (a.group.generators.push p.val)
  inside := by
    intro q hq
    apply hq.mono
    intro r hr
    simp only [Group.generators_ofGenerators, Array.mem_push] at hr
    rcases hr with hr | rfl
    · exact a.inside _ (.generator hr)
    · exact p.property
  satisfies := by
    intro q hq
    apply P.generated _ hq
    intro i
    have hi := Array.getElem_mem (xs := a.group.generators.push p.val) i.isLt
    simp only [Array.mem_push] at hi
    rcases hi with hi | hi
    · exact a.satisfies _ (.generator hi)
    · exact (congrArg P.test hi).trans hp

theorem adjoin_grows (a : Accumulator G P) (p : Element G) (hp : P.test p.val = true) :
    a.group.IsSubgroup (a.adjoin p hp).group := by
  intro q hq
  apply hq.mono
  intro r hr
  exact .generator (Array.mem_push.mpr (Or.inl hr))

theorem mem_adjoin (a : Accumulator G P) (p : Element G) (hp : P.test p.val = true) :
    Generated (a.adjoin p hp).group.generators p.val :=
  .generator (Array.mem_push.mpr (Or.inr rfl))

end Accumulator

/-- A traversal returns a growing checked subgroup and a certificate covering
every satisfying completion of its starting node. -/
structure Result {G : Group n} {P : Predicate n} (C : Constraint G P)
    (t : Node G) (a : Accumulator G P) where
  acc : Accumulator G P
  grows : a.group.IsSubgroup acc.group
  certificate : Certificate C.Reason
  checked : checkTree C acc.group t certificate = true

end Hex.PermGroup.Search
